### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by pathcl** [EMC-Underground/vsphere-python-restapi#3]
I think it should be included in setup.py some linting tool

pathcl@ladrillo:~/src/vsphere-python-restapi$ flake8 --statistics .
./myapi.py:1:1: F401 'url_for' imported but unused
./myapi.py:3:1: F401 'json' imported but unused
./myapi.py:10:1: E265 block comment should start with '# '
./myapi.py:10:40: W291 trailing whitespace
./myapi.py:13:1: E265 block comment should start with '# '
./myapi.py:14:1: E265 block comment should start with '# '
./myapi.py:15:1: E265 block comment should start with '# '
./myapi.py:17:1: E302 expected 2 blank lines, found 1
./myapi.py:21:1: E302 expected 2 blank lines, found 1
./myapi.py:25:1: E302 expected 2 blank lines, found 1
./myapi.py:29:1: E101 indentation contains mixed spaces and tabs
./myapi.py:29:1: W191 indentation contains tabs
./myapi.py:29:19: E251 unexpected spaces around keyword / parameter equals
./myapi.py:29:21: E251 unexpected spaces around keyword / parameter equals
./myapi.py:30:1: E101 indentation contains mixed spaces and tabs
./myapi.py:31:26: E251 unexpected spaces around keyword / parameter equals
./myapi.py:31:28: E251 unexpected spaces around keyword / parameter equals
./myapi.py:33:1: E302 expected 2 blank lines, found 1
./myapi.py:39:44: E231 missing whitespace after ','
./myapi.py:45:1: E303 too many blank lines (3)
./methods.py:18:5: E225 missing whitespace around operator
./methods.py:19:5: E225 missing whitespace around operator
./methods.py:20:4: E225 missing whitespace around operator
./methods.py:30:1: E302 expected 2 blank lines, found 1
./methods.py:33:34: W291 trailing whitespace
./methods.py:34:1: E302 expected 2 blank lines, found 1
./methods.py:40:44: E231 missing whitespace after ','
./methods.py:40:54: E231 missing whitespace after ','
./methods.py:42:21: F841 local variable 'ex' is assigned to but never used
./methods.py:48:14: W291 trailing whitespace
./methods.py:52:1: E302 expected 2 blank lines, found 1
./methods.py:52:43: E231 missing whitespace after ','
./methods.py:58:5: F841 local variable 'vm_json' is assigned to but never used
./methods.py:66:39: E231 missing whitespace after ','
./methods.py:73:39: E231 missing whitespace after ','
./methods.py:83:1: E302 expected 2 blank lines, found 1
./methods.py:87:1: E101 indentation contains mixed spaces and tabs
./methods.py:87:1: W191 indentation contains tabs
./methods.py:88:1: E101 indentation contains mixed spaces and tabs
./methods.py:88:21: E225 missing whitespace around operator
./methods.py:90:1: E101 indentation contains mixed spaces and tabs
./methods.py:90:1: W191 indentation contains tabs
./methods.py:90:2: E265 block comment should start with '# '
./methods.py:91:1: W191 indentation contains tabs
./methods.py:92:1: W191 indentation contains tabs
./methods.py:92:2: E101 indentation contains mixed spaces and tabs
./methods.py:93:1: E101 indentation contains mixed spaces and tabs
./methods.py:95:1: E101 indentation contains mixed spaces and tabs
./methods.py:95:1: W191 indentation contains tabs
./methods.py:96:1: W191 indentation contains tabs
./methods.py:97:1: W191 indentation contains tabs
./methods.py:97:3: E101 indentation contains mixed spaces and tabs
./methods.py:97:23: E231 missing whitespace after ','
./methods.py:97:25: E231 missing whitespace after ','
./methods.py:99:1: E101 indentation contains mixed spaces and tabs
./methods.py:108:1: E302 expected 2 blank lines, found 1
./methods.py:115:26: E251 unexpected spaces around keyword / parameter equals
./methods.py:115:28: E251 unexpected spaces around keyword / parameter equals
./methods.py:116:28: E251 unexpected spaces around keyword / parameter equals
./methods.py:116:30: E251 unexpected spaces around keyword / parameter equals
./methods.py:117:37: E231 missing whitespace after ':'
./methods.py:118:34: E231 missing whitespace after ':'
./methods.py:119:32: E231 missing whitespace after ':'
./methods.py:123:31: E251 unexpected spaces around keyword / parameter equals
./methods.py:123:33: E251 unexpected spaces around keyword / parameter equals
./methods.py:125:25: E251 unexpected spaces around keyword / parameter equals
./methods.py:125:27: E251 unexpected spaces around keyword / parameter equals
./methods.py:130:1: E302 expected 2 blank lines, found 1
./methods.py:135:28: E203 whitespace before ':'
./methods.py:135:38: E231 missing whitespace after ':'
./methods.py:139:1: E302 expected 2 blank lines, found 1
./methods.py:140:5: E265 block comment should start with '# '
./methods.py:149:5: E265 block comment should start with '# '
./methods.py:152:5: E265 block comment should start with '# '
./methods.py:159:1: E101 indentation contains mixed spaces and tabs
./methods.py:159:1: W191 indentation contains tabs
./methods.py:160:1: W191 indentation contains tabs
./methods.py:161:1: E101 indentation contains mixed spaces and tabs
./methods.py:161:1: W293 blank line contains whitespace
./methods.py:162:5: E265 block comment should start with '# '
./methods.py:165:1: W293 blank line contains whitespace
./methods.py:168:80: E501 line too long (90 > 79 characters)
./methods.py:169:1: E302 expected 2 blank lines, found 1
./methods.py:169:25: E231 missing whitespace after ','
./methods.py:170:5: E265 block comment should start with '# '
./methods.py:173:5: E265 block comment should start with '# '
./methods.py:178:1: E101 indentation contains mixed spaces and tabs
./methods.py:178:1: W191 indentation contains tabs
./methods.py:179:1: E101 indentation contains mixed spaces and tabs
./methods.py:179:1: W293 blank line contains whitespace
./methods.py:181:80: E501 line too long (81 > 79 characters)
./methods.py:182:1: E101 indentation contains mixed spaces and tabs
./methods.py:182:1: W191 indentation contains tabs
./methods.py:184:1: E101 indentation contains mixed spaces and tabs
./methods.py:187:1: E302 expected 2 blank lines, found 1
./methods.py:193:5: E265 block comment should start with '# '
./methods.py:195:5: E265 block comment should start with '# '
./methods.py:198:1: E101 indentation contains mixed spaces and tabs
./methods.py:198:1: W191 indentation contains tabs
./methods.py:199:1: W191 indentation contains tabs
./methods.py:199:2: E101 indentation contains mixed spaces and tabs
./methods.py:200:1: W191 indentation contains tabs
./methods.py:201:1: W191 indentation contains tabs
./methods.py:202:1: W191 indentation contains tabs
./methods.py:202:35: E225 missing whitespace around operator
./methods.py:203:1: W191 indentation contains tabs
./methods.py:203:33: E225 missing whitespace around operator
./methods.py:204:1: W191 indentation contains tabs
./methods.py:204:80: E501 line too long (101 > 79 characters)
./methods.py:205:1: W191 indentation contains tabs
./methods.py:206:1: W191 indentation contains tabs
./methods.py:207:1: W191 indentation contains tabs
./methods.py:207:2: E101 indentation contains mixed spaces and tabs
./methods.py:208:1: W191 indentation contains tabs
./methods.py:208:2: E101 indentation contains mixed spaces and tabs
./methods.py:209:1: W191 indentation contains tabs
./methods.py:209:80: E501 line too long (86 > 79 characters)
./methods.py:210:1: E101 indentation contains mixed spaces and tabs
./methods.py:210:80: E501 line too long (94 > 79 characters)
./methods.py:212:1: E101 indentation contains mixed spaces and tabs
./methods.py:212:1: W191 indentation contains tabs
./methods.py:213:1: W191 indentation contains tabs
./methods.py:213:2: E101 indentation contains mixed spaces and tabs
./methods.py:214:1: W191 indentation contains tabs
./methods.py:214:2: E101 indentation contains mixed spaces and tabs
./methods.py:216:1: E101 indentation contains mixed spaces and tabs
./methods.py:228:1: E302 expected 2 blank lines, found 1
./methods.py:230:75: E231 missing whitespace after ','
./methods.py:230:80: E501 line too long (89 > 79 characters)
./methods.py:234:1: E101 indentation contains mixed spaces and tabs
./methods.py:234:1: W191 indentation contains tabs
./methods.py:235:1: W191 indentation contains tabs
./methods.py:235:2: E101 indentation contains mixed spaces and tabs
./methods.py:236:1: E101 indentation contains mixed spaces and tabs
./methods.py:239:1: E302 expected 2 blank lines, found 1
./methods.py:245:80: E501 line too long (92 > 79 characters)
./methods.py:245:93: W291 trailing whitespace
./methods.py:253:1: E101 indentation contains mixed spaces and tabs
./methods.py:253:1: W191 indentation contains tabs
./methods.py:254:1: W191 indentation contains tabs
./methods.py:254:2: E101 indentation contains mixed spaces and tabs
./methods.py:257:1: E302 expected 2 blank lines, found 1
./methods.py:258:1: E101 indentation contains mixed spaces and tabs
./methods.py:273:1: E101 indentation contains mixed spaces and tabs
./methods.py:273:1: W191 indentation contains tabs
./methods.py:274:1: E101 indentation contains mixed spaces and tabs
./methods.py:281:80: E501 line too long (82 > 79 characters)
./methods.py:287:1: E101 indentation contains mixed spaces and tabs
./methods.py:287:1: W191 indentation contains tabs
./methods.py:288:1: W191 indentation contains tabs
./methods.py:288:2: E101 indentation contains mixed spaces and tabs
./methods.py:288:44: E231 missing whitespace after ','
./methods.py:289:1: W191 indentation contains tabs
./methods.py:290:1: E101 indentation contains mixed spaces and tabs
./methods.py:295:1: E302 expected 2 blank lines, found 1
./methods.py:315:49: E231 missing whitespace after ','
./methods.py:315:72: E231 missing whitespace after ','
./methods.py:315:80: E501 line too long (94 > 79 characters)
./methods.py:320:1: E101 indentation contains mixed spaces and tabs
./methods.py:320:1: W191 indentation contains tabs
./methods.py:320:11: E128 continuation line under-indented for visual indent
./methods.py:322:1: E101 indentation contains mixed spaces and tabs
./methods.py:330:1: E101 indentation contains mixed spaces and tabs
./methods.py:330:1: W191 indentation contains tabs
./methods.py:331:1: W191 indentation contains tabs
./methods.py:332:1: E101 indentation contains mixed spaces and tabs
./methods.py:334:1: E101 indentation contains mixed spaces and tabs
./methods.py:334:1: W191 indentation contains tabs
./methods.py:335:1: W191 indentation contains tabs
./methods.py:335:2: E101 indentation contains mixed spaces and tabs
./methods.py:337:1: E101 indentation contains mixed spaces and tabs
./methods.py:338:1: E101 indentation contains mixed spaces and tabs
./methods.py:338:1: W191 indentation contains tabs
./methods.py:340:1: W191 indentation contains tabs
./methods.py:341:1: W191 indentation contains tabs
./methods.py:343:1: W191 indentation contains tabs
./methods.py:343:2: E265 block comment should start with '# '
./methods.py:344:1: W191 indentation contains tabs
./methods.py:345:1: E101 indentation contains mixed spaces and tabs
45      E101 indentation contains mixed spaces and tabs
1       E128 continuation line under-indented for visual indent
1       E203 whitespace before ':'
6       E225 missing whitespace around operator
17      E231 missing whitespace after ','
12      E251 unexpected spaces around keyword / parameter equals
14      E265 block comment should start with '# '
17      E302 expected 2 blank lines, found 1
1       E303 too many blank lines (3)
9       E501 line too long (90 > 79 characters)
2       F401 'url_for' imported but unused
2       F841 local variable 'ex' is assigned to but never used
45      W191 indentation contains tabs
4       W291 trailing whitespace
3       W293 blank line contains whitespace

**Comment by quickjp2** [comment]
Indeed! Any suggestions?
